### ISSUE TITLE
completion auto-suggestion seems not working

### ISSUE THREAD

**Issue by yesvno** [randy3k/LaTeX-Plus#23]
As in the title, if I use the tex code in the screen shots, once I type in sec, no completion suggestions menu shows up unless I uncomment the second line. 

I am using default latex syntax package at the same time. It seems that there is a conflict between the auto-complete function of latex-plus and that of latex. If I type "\sec", a latex-plus completion popup will appear. If I select the snippet provide by latex syntax package, it results in double slash as below:

\\section{section name} % (fold)
\label{sec:section_name}

% section section_name (end)

Could you find a way to resolve this conflict?
BTW, it's an awesome plugin. Very light, but works for me in most of the times.

%%%%%

Below are the screen shots:
![2014-11-04 8 05 43](https://cloud.githubusercontent.com/assets/9551826/4899555/2f40248c-641d-11e4-9341-1dc8309be3b6.png)
![2014-11-04 8 06 49](https://cloud.githubusercontent.com/assets/9551826/4899556/32e69828-641d-11e4-8832-e819491c59c5.png)

**Comment by randy3k** [comment]
I believe the new way of triggering auto completion has solved this issue.
