### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by PeterPablo** [randy3k/LaTeX-Plus#25]
In my document there are cite commands like `\cite{author1997}`. Currently line wrapping can cut apart the that string at any location inside the curly braces. My own try to modify `LaTex Extended.tmLanguage` failed. Could you please give me a pointer?

I have comparable issues with formulas like `$\beta_v$`. Having the whole `\beta_v` as an undivideable group would be preferable in my opinion.

While at it, I also would prefer that `\sin{\varTheta_i}` sticks together completely.

**Comment by randy3k** [comment]
I have pushed some commits to address the issue of `\cite` and `\ref`. However, there is only a little I can do with `$\beta_v$` or `\sin{\varTheta_i}`. You can play around with the `word_separators` setting to see if you can get a format that you like.

**Comment by PeterPablo** [comment]
Thanks for your recent commits. Unfortunately the behavior of `\cite`is not improved. The default `latex` language scheme displays those in a better (non split) way. Manipulating `word_separators` doesn't seem to affect the wrapping.

Removing 
````
				<dict>
					<key>include</key>
					<string>#ref</string>
				</dict>
````
makes my `\cite`wish come true. Does it have unwanted side effects?

**Comment by randy3k** [comment]
I only fixed `\ref` and forgot to fix the `\cite`. It should look better now.

**Comment by PeterPablo** [comment]
I was wondering why a `git pull` wouldn't fetch that commit until I noticed that you pushed it to `LaTex-Plus` and `LaTex-Extended`. Would you please also update `LaTex-Extended` with that commit?

**Comment by randy3k** [comment]
`LaTex-Extended` is updated. :)

**Comment by PeterPablo** [comment]
Thanks! This specific issue is fixed. Would you please make `comment.latex` to wrap only at `word_separators`. Currently it wraps at any character.

**Comment by randy3k** [comment]
Fixed. :)

**Comment by PeterPablo** [comment]
Great!
Unfortunately `bla (bla) % my (comment)` can wrap behind the opening parenthesis `(`, even if I modify the `word_separators`.
A similar issue exists with `$\fex=\SI{1000}{\kilo\hertz}$`. I would expect that this is wrapped between the meeting curly braces `}{` and nowhere else. Is it possible for you to influence that? Also `$p$` in my opinion should only be wrapped as a whole.

Thank you for your fast response!

**Comment by randy3k** [comment]
There is only a little I can do with "where to break the line". The only setting can be used is `word_seperators`

**Comment by PeterPablo** [comment]
You did already a lot, so I am uncertain whether math-handling is any special. It is no dealbreaker for me so I am closing here. Thanks.

**Comment by randy3k** [comment]
Actually, why do you only interested in the syntax files but not the LaTeX-Plus?

**Comment by PeterPablo** [comment]
As I wrote in the commit comment (https://github.com/randy3k/LaTeX-Plus/commit/7860154f5777ee8c2d207e413e5258b1bed9f692#commitcomment-9502526) `LaTeX-Plus` is currently no option for me due to it not having multi-platform support.

**Comment by randy3k** [comment]
Why do you say so? It does support Mac, windows and Linux(Ubuntu).

**Comment by PeterPablo** [comment]
Sorry, my fault! I will reevaluate.
