### ISSUE TITLE
BracketHighlighter Settings

### ISSUE THREAD

**Issue by Kreger51** [randy3k/LaTeX-Plus#30]
After trying to figure out why BracketHighlighter was no longer showing unmatched brackets, I found out that what is suggested in [BracketHighlighter Settings](https://github.com/randy3k/Latex-Plus/wiki/BracketHighlighter-settings) (in Wiki) currently overrides all defaults in BracketHighlighter. 

This problem can easily be fixed by using "user_scope_brackets" and "user_brackets" instead of "scope_brackets" and "brackets", respectively. I got this information from [the BracketHighlighter documentation](https://github.com/facelessuser/BracketHighlighter#bracket-rule-management). 

I believe it would be nice to make the change in the wiki (would've made pull request but I don't think github supports Wiki pull requests?).

**Comment by randy3k** [comment]
@Kreger51, thanks for pointing it out. I have updated the wiki accordingly. 

Github doesn't support PR to wiki officially. But there is a [way](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) to do it.

**Comment by Kreger51** [comment]
Thanks for the link! I'll use that next time :)
