### ISSUE TITLE
Error code [12] ==> Undefined control sequence \IfUsePrefixLine

### ISSUE THREAD

**Issue by pattulus** [randy3k/LaTeX-Plus#33]
I'm not a LaTeX pro and I don't know if this is a `latexmk` issue or what it is, but I just wanted to let you know about this.

I have put a minimal working example [on Overleaf](https://www.overleaf.com/read/nkhyfffybvtb).

The file compiles fine with [Overleaf](https://www.overleaf.com/read/nkhyfffybvtb) or when I use `pdflatex` + `biber`:

    pdflatex "$1"; biber "$1"; pdflatex "$1"; pdflatex "$1"

With LaTeX-Plus I get one error which prevents the file from being compiled.

**Console Log:**

```bash
Compilation failed with return code [12]!

1 Error(s), 9 Warning(s), 0 FSC, and 1 BadBox(es).

[Error(s)]
E: mwe-working.tex:80    Undefined control sequence \IfUsePrefixLine.

[Warning(s)]
W: mwe-working.tex:0     Overwriting file `./literature.bib'.
W: mwe-working.tex:83    Citation 'Anderson:1999' on page 2 undefined.
W: mwe-working.tex:83    Citation 'Mann:1924' on page 2 undefined.
W: mwe-working.tex:83    Citation 'McGrane:2014' on page 2 undefined.
W: mwe-working.tex:88    Empty bibliography.
W: mwe-working.tex:0     old lof file detected, not used; run LaTeX again.
W: mwe-working.tex:0     File `mwe-working.out' has changed. Rerun to get outlines right or use package `bookmark'.
W: mwe-working.tex:0     There were undefined references.
W: mwe-working.tex:0     Please (re)run Biber on the file: mwe-working and rerun LaTeX afterwards.

[BadBox(es)]
B: mwe-working.tex:83    Overfull \hbox (23.30411pt too wide)

[Done in 2.43s!]
```

_PS: Don't mind the citation warnings… when not using a listfiles bibliography everything is fine there._

_PPS: Maybe related: [sectioning - KOMA-Script: How to style the title of a chapter - TeX - LaTeX Stack Exchange](http://tex.stackexchange.com/questions/246411/koma-script-how-to-style-the-title-of-a-chapter)_

**Comment by randy3k** [comment]
I have no problem in compiling your example. I guess it is due to a missing/outdated package. I suggest your update all your packages to see if it solves the problem.

**Comment by pattulus** [comment]
Thanks for the pointer @randy3k. It's good to know that it works on your side. I'll figure it out.
