### ISSUE TITLE
Is there a shortcut for langle?

### ISSUE THREAD

**Issue by pluskid** [randy3k/LaTeX-Plus#34]
Thanks for this amazing project. I use vim for everything else but use sublime text for tex files because of this fantastic plugin. I especially find the shortcut for typing brackets with `\left-\right` very useful. Another pair of symbols that I typed a lot is `\langle x, y \rangle` for inner products. I think it would be really great if we could also have a convenient way of typing `\langle  \rangle` (and possibly with `\left-\right`). Thanks!

**Comment by randy3k** [comment]
Do you think if `<<` would be a good keybind for `\langle` and `\rangle`?

**Comment by pluskid** [comment]
Yes, while `<` is definitely used everywhere, maybe it is sensible to map `<<` to `\langle \rangle`, and typing an extra `<` expand to `\left\langle \right\rangle`? (like those mapping for `\left\{ \right\}`).

**Comment by randy3k** [comment]
I think  `<<` is a valid math notation. `x << y` means `x` is much smaller than `y`. So `<<` may not be a very good keybind for it.....

**Comment by pluskid** [comment]
Yes but \ll and \gg should be used in that case. Typing << directly does not produce a correctly looking "much smaller than" math symbol

**Comment by randy3k** [comment]
How about `<<` to insert `\ll`, `\<` for the `\langle` pair and `\<<` for `\left\langle` pair?

**Comment by pluskid** [comment]
yes that would be very nice! :)

**Comment by randy3k** [comment]
Done f483a701d2113d8349c6bb665f2e28d02b82147d.

**Comment by pluskid** [comment]
@randy3k Thanks! The update has been working very nicely. Just a minor refinement:
maybe `\<` could expand to `\lange | \rangle` -- `|` is the cursor, and with spaces around the cursor. This is because without spaces, if I type any letter, say `x` immediately after expanding, I will get `\langlex\rangle`, which is invalid latex. I'm OK with the current expansion though, but I feel the refinement will make it more user friendly.

**Comment by randy3k** [comment]
Actually, in my original implementation, `\<` expands to what you have wanted. But this makes the logic behind the deletion of the pair and the expansion to `\left\langle\right\angle` become more complicated. Thus I decided to keep it as is.

**Comment by pluskid** [comment]
Thanks for the clarification!
