### ISSUE TITLE
Bug with Biblatex @online Reference

### ISSUE THREAD

**Issue by SGL483** [randy3k/LaTeX-Plus#35]
I use the biblatex package (https://www.ctan.org/pkg/biblatex) to create my bibliography. I have several online (@online) references in my Literature.bib. I cannot select these entries in the cite auto completion box. @article entries work fine.

Is there are way to automatically show the auto completion box after \cite{ instead of pressing the keys?

Thank you very much for your good work at Latex-Plus!

**Comment by SGL483** [comment]
Here is a list of all supported biblatex entries: article, book, mvbook, inbook, bookinbook, suppbook, booklet, collection, mvcollection, incollection, suppcollection, manual, misc, online, patent, periodical, suppperiodical, proceedings, mvproceedings, inproceedings, reference, mvreference, inreference, report, set, thesis, unpublished, conference, electronic, mastersthesis, phdthesis, techreport, www

**Comment by randy3k** [comment]
I have added the list. See if it works now.

For the keybind, you could define your own keybind for the the `\cite`. I didn't do so since there are a few similar commands. `\cite`, `\ciitep`, `\citeauthor` and `\citeyear` etc.

**Comment by SGL483** [comment]
Hey Randy, Thanks for the update. It works great now. But this is strange: a @collection entry does not have an author but only a publisher. In the auto completion box it looks like this: (2008): Book title. It doesn't show the publisher's name.

**Comment by randy3k** [comment]
For now, the only three fields showing are author, title and year.
I think I am not fixing the @collection and publisher problem. As there might be a lot of other exceptions to be take care of....I would rather keep the code clean.

**Comment by SGL483** [comment]
I understand your point very well. You could read author and publisher and use publisher only if author is empty (for all entries not only for @collection). What do you think of this idea?

**Comment by randy3k** [comment]
Implemented! 27d3f7b5fa7924955f5cbac04ba6cf027db27d98 

Whenever the author field is missing, it would be replaced by the publisher.

**Comment by SGL483** [comment]
Thank you very much! It works perfect now.
