### ISSUE TITLE
Copy/paste of BracketHighlighter-settings fails 

### ISSUE THREAD

**Issue by Naereen** [randy3k/LaTeX-Plus#36]
Thanks for the new [page about BracketHighlighter-settings](https://github.com/randy3k/LaTeX-Plus/wiki/BracketHighlighter-settings)!
The custom brackets works fine and are a good idea :+1: !

But could you please either provide the ``bh-core.sublime-settings`` as a raw file (like [this gist](https://gist.github.com/Naereen/90be74c38197a6ff02fa)), or (try to) fix the file included in the new wiki page?

It has a weird bug when copying/pasting the lines for ``open`` and ``close`` tags for the first ``latex_plus_left_right`` custom bracket:

  ``"(\\\\left(?:[()\\[\\]]\\\\[{}]\\\\[a-zA-Z]+))"`` got copied as ``"(\\\\left(?:[()\\[\\]"]"\\\\[{}"]"\\\\[a-zA-Z]+))"`` : alone ``]`` gets altered (in your version on the wiki) as ``"]"``.

*Note:* this might be a Linux / Firefox specific bug, I have not tried on any other platform.

**Comment by Naereen** [comment]
Ok, so the ``BracketHighlighter-settings.md`` file is correct, so I guess it's a bug from GitHub syntax highlighter for JSON file.
Sorry, I guess this cannot be fixed here.

**Comment by randy3k** [comment]
I don't 100% understand what you mean.... 
However, there are some bugs in BracketHighlighter settings page, please refer to the newest update.

**Comment by Naereen** [comment]
I was saying that a simple copy/paste of the content of the proprosed ``bh-core.sublime-settings`` file from [that Wiki page]() bugs (on Firefox).
The pasting weirdly adds double quote (``"``) around the closing ``]`` for

**Comment by randy3k** [comment]
Mac Safari doesn't have such an issue...

**Comment by Naereen** [comment]
OK. So that's a weird bug, probably only concerning Firefox, or Firefox on Linux, or .. just myself.
Sorry.
You can close it I guess :v: !

**Comment by randy3k** [comment]
Okay.
